cargo-features = ["edition2021"]
[package]
name = "beginning_linux_programming"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2"

[dev-dependencies]
anyhow = "1.0"
futures = "0.3"
# gtk4 = "0.2"
